config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  resources :ingredients

  root 'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    @recipes = Recipe.all
  end

  # GET /ingredients/1/edit
  def edit
    @recipes = Recipe.all
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :recipe_ids => [])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :directions, :ingredient_ids => [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Food App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
  <div class="large-12 columns">

    <h1>Listing ingredients</h1>
    <%= link_to 'New Ingredient', new_ingredient_path %>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Recipes</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @ingredients.each do |ingredient| %>
          <tr>
            <td><%= ingredient.name %></td>
            <td><%= ingredient.recipes.map { |r| r.name }.join(', ') %></td>
            <td><%= link_to 'Show', ingredient %></td>
            <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
            <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.recipes.map { |r| r.name }.join(', ') %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <!-- Header Stuff -->
      <div class="large-3 columns">
        <h1>Food App</h1>
      </div>
      <!-- Header Stuff -->
    </div>
    <div class="row">
      <!-- Actual Body -->
      <%= yield %>
      <!-- Actual Body -->
    </div> 
    <div class="row">
      <!-- Footer Stuff -->
      <div class="large-12 columns pull-right">
        <%= link_to "Home",        root_path %>
        <%= link_to "About",       about_path %>
        <%= link_to "Recipes",     recipes_path %>
        <%= link_to "Ingredients", ingredients_path %>
      </div>
      <!-- Footer Stuff -->
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="large-12 columns">
  <h1>Listing recipes</h1>
  <%= link_to 'New Recipe', new_recipe_path %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Directions</th>
        <th>Ingredients</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @recipes.each do |recipe| %>
        <tr>
          <td><%= recipe.name %></td>
          <td><%= recipe.description %></td>
          <td><%= recipe.directions %></td>
          <td><%= recipe.ingredients.map { |i| i.name }.join(', ') %></td>
          <td><%= link_to 'Show', recipe %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @recipe.directions %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="large-9 columns">
	<h3 class="subheader">About this food app</h3>
	<p>
		The food app is something I want to make for myself to help me decide what to make for dinner. That's about it. Well, there's more to come in the future but in the meantime there's a database of recipes that I know I like and the robot will tell me what to eat. 
	</p>
	<h4 class="subheader">Down the road</h4>
	<p>
		I will implement something that will give me suggestions base on the ingredients I have on hand, taking into consideration what I ate yesterday and the day before, what I traditionally eat on Thursdays and whatever other criteria I come up with between now and then. 
	</p>
	<p>
		For now this thing is just a project to get me back into the Rails groove again and it'll probably stay here for good as virtually every recipe site has this functionality already. But who knows...
	</p>
</div>

app/views/static_pages/home.html.erb
<div class="large-12 columns">
	<!-- Test for signed in user and remove this if signed in -->
	<div class="panel text-center" id="home-panel">
		<h1>Welcome to the Food App!</h1>
		<p>
			This is such a great app! The Food App is your own personal decision maker. You'll never not know what to eat again!
		</p>
		<%= link_to "Try it out!", '#', :class => 'button' %>
	</div>
</div>